name = "CrystalNets"
uuid = "7952bbbe-a946-4118-bea0-081a0932faa9"
authors = ["Lionel Zoubritzky lionel.zoubritzky@gmail.com"]
version = "0.5.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
Chemfiles = "46823bd8-5fb3-5f92-9aa0-96921f3dd015"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
PeriodicGraphEmbeddings = "f305370e-dc8e-427a-bb15-d3949eabeccf"
PeriodicGraphEquilibriumPlacement = "72a2d4b8-adbf-4c88-a101-42c807716bb0"
PeriodicGraphs = "18c5b727-b240-4874-878a-f2e242435bab"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
ArgParse = "1.1"
Chemfiles = "0.10"
Graphs = "1.3"
LinearAlgebra = "1.6"
Logging = "1.6"
PeriodicGraphEmbeddings = "0.3.0"
PeriodicGraphEquilibriumPlacement = "0.2"
PeriodicGraphs = "0.10"
Pkg = "1.6"
PrecompileTools = "1"
ProgressMeter = "1.7"
Serialization = "1.6"
StaticArrays = "0.12.4, 1.0"
Statistics = "1.6"
julia = "1.6"
